### ISSUE TITLE
panzoom and mousewheel

### ISSUE THREAD

**Issue by piller187** [sdrdis/jquery.flowchart#15]
I pulled the panzoom and mousewheel from your advanced example. I'm using jquery 3.1.1. I include jquery and jquery.ui and then in this order the other files:

    <script src="~/Scripts/jquery.panzoom.min.js"></script>
    <script src="~/Scripts/jquery.mousewheel.min.js"></script>
    <script src="~/Scripts/jquery.flowchart.js"></script>

but I'm getting an error: 

jquery.panzoom.min.js:83 Uncaught TypeError: Cannot read property 'concat' of undefined
    at http://localhost:63145/Scripts/jquery.panzoom.min.js:83:20
    at http://localhost:63145/Scripts/jquery.panzoom.min.js:11:158
    at http://localhost:63145/Scripts/jquery.panzoom.min.js:12:2

**Comment by sdrdis** [comment]
Ok that means I need to update it. Thanks, I will try to do it shortly (I am a bit under the water at the moment that is why I take some time to answer...)
